name: Deploy to EC2

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Test SSH Connection
      run: |
        cd /projects; ls -la'

    - name: Copy files to EC2
      run: |
        scp -r -o StrictHostKeyChecking=no . ec2-user@${{ secrets.EC2_HOST }}:projects/blisscart

    - name: SSH into EC2 buil and deploy
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
        cd projects/blisscart/
        docker-compose down
        docker-compose up --build -d
        EOF
