name: Deploy to EC2

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Copy files to EC2
      run: |
        scp -r -o StrictHostKeyChecking=no . ec2-user@<${{ secrets.EC2_HOST }}>:/path/to/your/project/

    - name: SSH into EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@<${{ secrets.EC2_HOST }}> << 'EOF'
        cd /projects/blisscart/
        docker-compose down
        docker-compose up --build -d
        EOF



name: Deploy to EC2

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy project to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude target ./ ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/projects/blisscart

      - name: Build and run Docker container on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << EOF
            cd /home/ec2-user/projects/blisscart
            docker build -t blisscart-app .
            docker stop blisscart-container || true
            docker rm blisscart-container || true
            docker run -d --name blisscart-container -p 8080:8080 blisscart-app