name: Deploy to EC2

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to EC2
      run: |
        scp -r -o StrictHostKeyChecking=no . ec2-user@<your-ec2-ip>:/path/to/your/project/

    - name: SSH into EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@<your-ec2-ip> << 'EOF'
        cd /path/to/your/project/
        docker-compose down
        docker-compose up --build -d
        EOF
