name: Test and Deploy

on:
  push:
    branches:
      - Development

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build and test
        run: mvn clean verify

      - name: Merge to deployment branch
        if: success()
        uses: actions/checkout@v3
        with:
          args: |
            git config user.name "Brian-Mulei"
            git config user.email "brianmulei0@gmail.com"
            git checkout deployment
            git merge development
            git push origin deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
