name: Test and Deploy

on:
  push:
    branches:
      - Development

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      REGION: ${{ secrets.REGION }}
      BUCKET: ${{ secrets.BUCKET }}
      AWS_ID: ${{ secrets.AWS_ID }}
      AWS_KEY: ${{ secrets.AWS_KEY }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build and test
        run: mvn clean verify

      - name: Merge to deployment branch
        if: success()
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          args: |
            git config user.name "Brian-Mulei"
            git config user.email "brianmulei0@gmail.com"
            git fetch origin
            git checkout deployment
            git pull origin deployment   
            git merge Development
            git push origin deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
